build: reworked docker config

diff --git a/.docker/php/Dockerfile b/.docker/php/Dockerfile
--- a/.docker/php/Dockerfile
+++ b/.docker/php/Dockerfile
@@ -1,10 +1,5 @@
 FROM php:7.4-fpm-buster
 
-# Arguments defined in docker-compose.yml
-ARG uname
-ARG gid
-ARG uid
-
 # Install system dependencies
 RUN apt-get update && apt-get upgrade -y && apt-get install -y \
   git \
@@ -19,43 +14,37 @@ RUN apt-get update && apt-get upgrade -y && apt-get install -y \
   zip \
   unzip \
   cron \
+  default-mysql-client \
   mc
 
-# Install PHP extensions
+
+# PHP
 RUN docker-php-ext-configure gd \
   --enable-gd \
   --with-jpeg && \
-  docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip opcache mysqli && \
+  docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip mysqli && \
   pecl install xdebug && \
   docker-php-ext-enable mysqli xdebug
 
-# Clear cache
+
+# Composer & WP-Cli
+RUN set -xe \
+    && curl -L -o /composer.phar https://github.com/composer/composer/releases/download/2.0.12/composer.phar \
+    && chmod 755 /composer.phar \
+    && curl -L -o /wp-cli.phar https://github.com/wp-cli/wp-cli/releases/download/v2.4.0/wp-cli-2.4.0.phar \
+    && chmod 755 /wp-cli.phar
+
+# Cleanup
 RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*
 
-# php config
-ADD ./php.ini /usr/local/etc/php/php.ini
-# opcache config
-ADD opcache.ini "$PHP_INI_DIR/conf.d/opcache.ini"
 
-# Get latest Composer
-COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
+WORKDIR /var/www/wordpress
 
-ARG wp_version
-ARG wc_version
+COPY entrypoint.sh /
+RUN chmod 755 /entrypoint.sh
 
-# Create system user to run Composer
-RUN groupadd --gid $gid $uname && \
-  useradd -G www-data,root -s /bin/bash --uid $uid --gid $gid $uname && \
-  mkdir -p /home/$uname/.composer && \
-  chown -R $uname:$uname /home/$uname && \
-  composer create-project roots/bedrock . && \
-  composer require wpackagist-plugin/woocommerce:$wc_version && \
-  composer require roots/wordpress:$wp_version && \
-  composer require wpackagist-plugin/wp-mail-logging && \
-  chmod 777 /var/www/html/web/app/uploads && \
-  touch /var/www/xdebug.log && chown $uname:$uname /var/www/xdebug.log
-
-# Set working directory
-WORKDIR /var/www/html
-
-USER $uname
+# avoid the docker initialization
+# see https://github.com/docker/compose/issues/1809
+ENTRYPOINT ["/entrypoint.sh"]
+EXPOSE 9000
+CMD ["php-fpm"]
